# NumPy 

NumPy (for Numerical Python) is a Linear Algebra Library for Python. This library is regarded as one of the most important libraries because a lot of other libraries in the Python Ecosystem depend on Numpy as their main building block.


Numpy consists of multidimensional array objects and a collection of routines for processing those arrays. Numpy is an incredibly fast library which lends increased efficiency to other libraries too. 


Here, we shall discuss the basics of NumPy, it's architecture and environment. We also discuss the various array functions, types of indexing, etc. 


## Some History!

Numeric, the ancestor of NumPy, was developed by Jim Hugunin. Another package Numarray was also developed, having some additional functionalities. In 2005, Travis Oliphant created NumPy package by incorporating the features of Numarray into Numeric package. There are many contributors to this open source project.


## What can be done using numpy?


Using NumPy, a data scientist can perform the following operations −

- Mathematical and logical operations on arrays.
- Shape manipulations
- Linear algebra. NumPy has in-built functions for linear algebra and random number generation.

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np


# Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
list1 = [1,2,3]
list1

[1, 2, 3]

In [4]:
np.array(list1)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

In [ ]:
np.array(my_matrix)

### arange

Return evenly spaced values within a given interval.

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [16]:
np.random.rand(2)

array([0.78909228, 0.07450393])

In [17]:
np.random.rand(5,5)

array([[0.00224153, 0.95690705, 0.47979342, 0.47229138, 0.52155818],
       [0.94379297, 0.75620321, 0.22530354, 0.00353073, 0.98259358],
       [0.89248113, 0.94697072, 0.42272031, 0.52286777, 0.91415092],
       [0.19527185, 0.72430208, 0.80921411, 0.32817371, 0.76046238],
       [0.20525048, 0.59062256, 0.18738569, 0.60016818, 0.62556004]])

## Slicing and Indexing


In [19]:
#Creating sample array
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
#Get a value at an index
arr[8]

18

In [21]:
#Slicing 
arr[1:5]

array([11, 12, 13, 14])

#### Indexing & Slicing in 2D Array: 

In [25]:
# Create an 2d array: 
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
# Let's find out value '25' using indexing: 
arr_2d[1]  #Step 1

array([20, 25, 30])

In [29]:
arr_2d[1][1] # Step 2

25

**Another Method** (Recommended)

In [30]:
# Getting individual element value
arr_2d[1,1]

25

#### Fancy Indexing: 

Fancy indexing allows us to index the rows and columns in multiple sets and in any order. 

In [34]:
arr_2d[[1,2],[0]]

array([20, 35])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [22]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [23]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr



##### Good Job!