# Numpy Operations

In this lecture we discuss some useful numpy operations. Most of these are borrowed from basic linear algebra and includes the concepts like matrix sum , matrix multiplication etc. 



In [2]:
import numpy as np

In [5]:
# Creating two arrays

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x,"\n", y )


[[1. 2.]
 [3. 4.]] 
 [[5. 6.]
 [7. 8.]]


#### Addition:

In [6]:
print(x)
print(y)
# Matrix sum:  ( element wise )
print(x + y)
print( np.add(x , y))


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


#### Subtraction:

In [7]:
# Matrix subtraction : ( element wise )
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


#### Product:

In [ ]:
# Elementwise product
print(x * y)
print(np.multiply(x, y))



#### Division:

In [ ]:
# Elementwise division
print(x / y)
print(np.divide(x, y))


### Dot Product:

In [10]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [11]:
# Inner product of vectors; both produce 219

print(v.dot(w))
print(np.dot(v, w))

219
219


In [12]:

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))


[29 67]
[29 67]


In [13]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Misc Operations: 

In [15]:
arr = np.arange(0,11)

In [16]:
#Taking Square Roots
np.sqrt(arr)

#Calcualting exponential (e^)
np.exp(arr)

#Calculating the max 
np.max(arr) #same as arr.max()

# Trignometry example:
np.sin(arr)

#Log:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

**A look at the documentation** (Optional, but recommended): 

Numpy is a huge library that consists of plenty of stuff. It may be good idea to scroll through its [official documentation](https://scipy-lectures.org/intro/numpy/operations.html) and see what more can be done using numpy. 

##### Congratulations!