In [51]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [52]:
x

array([[1, 2],
       [3, 4]])

In [53]:
y

array([[5, 6],
       [7, 8]])

In [54]:
x - y

array([[-4, -4],
       [-4, -4]])

In [55]:
np.add(x , y)

array([[ 6,  8],
       [10, 12]])

In [56]:
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

In [57]:
print(x * y)
print(np.multiply(x, y))


[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [58]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [59]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [60]:
v

array([ 9, 10])

In [61]:
w

array([11, 12])

219

In [62]:
x

array([[1, 2],
       [3, 4]])

In [63]:
y

array([[5, 6],
       [7, 8]])

In [67]:
v.dot(w)
np.dot(v,w)


219

In [69]:
np.dot(x , y)

array([[19, 22],
       [43, 50]])

In [70]:

arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [71]:
np.sqrt(arr)

array([ 0.        , 10.        , 10.        , 10.        , 10.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])